root: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - svelte3
  - '@typescript-eslint'
ignorePatterns:
  - '*.cjs'
overrides:
  - files:
      - '*.svelte'
    processor: svelte3/svelte3
settings: {}
rules:
  indent: [error, tab]
  quotes: [error, single]
  semi: [error, never]
parserOptions:
  sourceType: module
  ecmaVersion: 2020
env:
  browser: true
  es2017: true
  node: true

